name: "demo_h5"

on:
  push:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Install h5py mpi4py
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install universe python3-h5py python3-mpi4py

    - name: Checkout
      uses: actions/checkout@v4
    - name: Test demo_h5
      run: |
        python test/demo_h5.py
