name: lin spack h5py

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Fortran
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gcc
        version: 13
    - name: Checkout Spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        path: ./spack
    - name: Run a multi-line script
      run: |
        ./spack/bin/spack install py-h5py@master ^openblas@develop
        ./spack/bin/spack install py-pytest
        ./spack/bin/spack install py-ipython
        ./spack/bin/spack install py-pip
        . ./spack/share/spack/setup-env.sh
        spack load py-h5py
        spack load py-pytest
        spack load py-ipython
        spack load py-pip
        pip install pytest-mpi
        ls test
        mpirun -np 2 python test/demo_h5.py
	h5dump parallel_test.hdf5
