name: swmr_mp

on:
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: windows-latest
    steps:
    - name: install hsds
      run: |
        pip install hsds
    - name: start server
      run: |
        hsds --root_dir ~/hsds_data
      shell: bash